FROM osrm/osrm-backend
WORKDIR /osrm-data

# 1. Instalar la herramienta de descarga (wget)
RUN apt-get update && \
    apt-get install -y wget && \
    rm -rf /var/lib/apt/lists/*

# 2. Descargar el archivo PBF de Perú (Ahora funcionará)
RUN wget https://download.geofabrik.de/south-america/peru-latest.osm.pbf -O peru.osm.pbf

# 3. Preprocesar los datos
RUN osrm-extract -p /opt/osrm-backend/profiles/car.lua peru.osm.pbf
RUN osrm-partition peru.osrm
RUN osrm-customize peru.osrm

# 4. Limpiar el archivo PBF original
RUN rm peru.osm.pbf

# 5. Definir el comando por defecto
CMD ["osrm-routed", "--algorithm", "mld", "peru.osrm"]